version: '3.3'

services:

  postgresql:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./.docker/pgadmin/data:/var/lib/pgadmin
      - ./.docker/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
